### ISSUE TITLE
Add: Create own GitHub account

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/FirstPhoneBook#2]
- [x] Read [Creating an own GitHub account](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/OwnGitHubAccount/OwnGitHubAccount.md)
- [x] Create a GitHub account
- [x] Send user name to ApplicationOwners@openBackhaul.com by email
- [x] Close this issue

**Comment by PrathibaJee** [comment]
I have a GitHub account already, so I didnt create a new one. Sent an email about my user name to the mentioned email.
