### ISSUE TITLE
Add: Install Git

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/FirstPhoneBook#3]
- [x] Read [Installing and Configuring Git](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/InstallingGit/InstallingGit.md)
- [x] Install Git
- [x] Close this issue

**Comment by PrathibaJee** [comment]
I already have Git installed in my system. So, gone through the study material and closing the issue.
